include: ../main.yaml

model:
  name: positional
  n_layer: 7
  n_head: 6
  n_embd: 240
  block_size: 128
  dropout: 0.0
  bias: false

task:
  name: kv
  params:
    k_card: 64
    v_card: 64
    n_pairs: 31
  n_val: 1000

optimizer:
  learning_rate: 0.0006
  min_lr: 6.0e-05
  warmup_iters: 225
  lr_decay_iters: 4500

train:
  init: scratch
  batch_size: 8
  gradient_accumulation_steps: 32
  max_iters: 4500
  eval_interval: 250
  eval_iters: 6400

paths:
  run_dir: runs/EVE-PE/medium
