include: ../main.yaml

model:
  name: positional
  n_layer: 4
  n_head: 4
  n_embd: 128
  block_size: [256, 384]
  dropout: 0.0
  bias: false
  pos_encoding: [nope, rope, wpe]

task:
  name: kv_retrieval
  params:
    k_card: 80
    v_card: 80
    n_pairs: [2, 25]
  n_val: 1000

optimizer:
  name: adamw
  decay: matrices
  schedule: cosine
  learning_rate: 0.0001
  min_lr: 1.0e-05
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  warmup_iters: 100
  lr_decay_iters: 57000
  grad_clip: 1.0

train:
  init: scratch
  seed: 1337
  batch_size: 256
  gradient_accumulation_steps: 1
  max_iters: 57000
  eval_interval: 250
  eval_iters: 100
  reproducible_val: false
  early_stop_patience: 0

paths:
  run_dir: runs/EVE-PE/paper_pe
