
model:
  name: positional
  n_layer: 4
  n_head: 4
  n_embd: 128
  block_size: 256
  dropout: 0.0
  bias: false

task:
  name: kv_retrieval
  params: {k_card: 80, v_card: 80, n_pairs: [2, 25]}  
  n_val: 1000

paths:
  run_dir: runs/small

train:
  init: scratch
  batch_size: 256
  gradient_accumulation_steps: 1
  max_iters: 80000
  eval_interval: 250
  eval_iters: 100

optimizer:
  lr_decay_iters: 80000
  warmup_iters: 100
  learning_rate: 1.0e-4
  min_lr: 1.0e-5
  weight_decay: 0.1
