
include: base.yaml

paths:
  run_dir: runs/depth/add_loop

model:
  name: looped
  n_layer: 1  
  n_loops: [1, 2, 4, 8, 12]
  block_size: 53

task:
  name: [add_seq, add_indep]
  params: {n_digits: 16}

train:
  seed: [0, 1, 2]
