
include: base.yaml

paths:
  run_dir: runs/depth/sort_grid

model:
  n_layer: [2, 4, 8]
  n_embd: [128, 256, 512]
  n_head: 0  
  block_size: 17  

task:
  name: sorting
  params: {v_card: 52, n_items: 8, duplicates: true}

train:
  seed: 0
  eval_interval: 1000
