include: size/small.yaml

hardware:
  device: gpu
  gpu: 0
  dtype: bfloat16
  compile: false

model:
  name: positional
  pos_encoding: [nope, rope, wpe]
  block_size: [256, 384]

task:
  name: kv_retrieval
  params: {k_card: 80, v_card: 80, n_pairs: [2, 25]}   
  n_val: 1000

train:
  init: scratch
  seed: 1337          
  max_iters: 57000
  batch_size: 256
  gradient_accumulation_steps: 1
  eval_interval: 250
  eval_iters: 100

paths:
  run_dir: runs/paper_pe

optimizer:
  lr_decay_iters: 57000
  warmup_iters: 100
  learning_rate: 1.0e-4
  min_lr: 1.0e-5
  weight_decay: 0.1
