include: ../main.yaml

model:
  name: depth
  n_layer: 4
  n_head: 0
  n_embd: [128, 256, 512]
  block_size: 16
  dropout: 0.0
  bias: true

task:
  name: s5
  params:
    n_perms: 8
  n_val: 5000
  n_train: 1000000

optimizer:
  name: adamw
  decay: all
  learning_rate: 0.0003
  min_lr: 0.0
  weight_decay: 0.1
  warmup_iters: 500
  lr_decay_iters: 60000
  grad_clip: 1.0

train:
  init: scratch
  seed: [0, 1, 2]
  batch_size: 8
  gradient_accumulation_steps: 32
  max_iters: 60000
  eval_interval: 2000
  eval_iters: 64

hardware:
  dtype: float32

paths:
  run_dir: runs/depth-experiments/perm_width
