include: ../main.yaml

model:
  name: depth
  n_layer: [2, 4, 8]
  n_head: 0
  n_embd: [128, 256, 512]
  block_size: 17
  dropout: 0.0
  bias: true

task:
  name: sorting
  params:
    v_card: 52
    n_items: 8
    duplicates: true
  n_val: 5000
  n_train: 100000

optimizer:
  name: adamw
  decay: all
  learning_rate: 0.0003
  min_lr: 0.0
  weight_decay: 0.1
  warmup_iters: 500
  lr_decay_iters: 20000
  grad_clip: 1.0

train:
  init: scratch
  seed: 0
  batch_size: 256
  gradient_accumulation_steps: 1
  max_iters: 20000
  eval_interval: 1000
  eval_iters: 2

hardware:
  dtype: float32

paths:
  run_dir: runs/depth-experiments/sort_grid
